CREATE TABLE IF NOT EXISTS workspace_state (
  id TEXT PRIMARY KEY NOT NULL,
  payload TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ai_usage (
  date TEXT PRIMARY KEY NOT NULL,
  used INTEGER NOT NULL DEFAULT 0
);
